### ISSUE TITLE
SampleDemo Crash

### ISSUE THREAD

**Issue by yangchendev** [eleme/UETool#15]
### Issue Description
运行sampleDemo会发生crash
#### Description
java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ele.uetool.base.Element.reset()' on a null object reference
        at me.ele.uetool.EditAttrLayout$ShowMode$2.onDismiss(EditAttrLayout.java:188)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1361)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by yangchendev** [comment]
场景就是打开了右边subMenu点下第一个按钮，再按下home键就会crash

**Comment by JeasonWong** [comment]
感谢你的反馈，可以尝试拉下最新代码或者使用 v1.0.14.

Thanks for your report, please try to pull lasted code or compile v1.0.14. 😊
