### ISSUE TITLE
运行demo闪退，是否需要额外操作？

### ISSUE THREAD

**Issue by nowtf** [eleme/UETool#26]
#### Description

从 github clone 项目，然后在 AS 中打开运行，直接闪退。错误信息如下：

me.ele.uetool.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: me.ele.uetool.sample, PID: 16578
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ele.uetool.sample/me.ele.uetool.sample.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:me.ele.uetool.sample flg=0x10000000 }
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2717)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                          at android.os.Looper.loop(Looper.java:191)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5960)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
                                                                       Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION dat=package:me.ele.uetool.sample flg=0x10000000 }
                                                                          at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1831)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
                                                                          at android.app.ContextImpl.startActivity(ContextImpl.java:705)
                                                                          at android.app.ContextImpl.startActivity(ContextImpl.java:687)
                                                                          at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
                                                                          at me.ele.uetool.UETool.requestPermission(UETool.java:134)
                                                                          at me.ele.uetool.UETool.showMenu(UETool.java:89)
                                                                          at me.ele.uetool.UETool.showMenu(UETool.java:83)
                                                                          at me.ele.uetool.UETool.showUETMenu(UETool.java:63)
                                                                          at me.ele.uetool.sample.MainActivity$1.onCheckedChanged(MainActivity.java:33)
                                                                          at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
                                                                          at android.support.v7.widget.SwitchCompat.setChecked(SwitchCompat.java:1056)
                                                                          at me.ele.uetool.sample.MainActivity.onCreate(MainActivity.java:41)
                                                                          at android.app.Activity.performCreate(Activity.java:6361)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2670)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                          at android.os.Looper.loop(Looper.java:191) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5960) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821) 

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by JeasonWong** [comment]
请进入手机设置并打开 UETool demo 的悬浮窗权限
please open floating window permission in phone setting
