### ISSUE TITLE
Can't work with XiaoMi 8

### ISSUE THREAD

**Issue by dobabby** [eleme/UETool#31]
### Issue Description

当打开捕捉功能后 选中任意视图均提示 无法在当前位置找到视图。

#### Description

MIUI 9.5 稳定版

Android 8.1

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

有可能是无法在异形全面屏手机正常工作

[Add anything else here]

**Comment by dobabby** [comment]
E/ContentCatcherManager: failed to get ContentCatcherService.

**Comment by dobabby** [comment]
06-14 09:43:41.743 14803-14803/com.dstcar.client W/System.err: java.lang.ClassNotFoundException: me.ele.uetool.fresco.UETFresco
06-14 09:43:41.748 14803-14803/com.dstcar.client W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at me.ele.uetool.AttrsDialog$Adapter.notifyDataSetChanged(AttrsDialog.java:129)
        at me.ele.uetool.AttrsDialog.show(AttrsDialog.java:86)
        at me.ele.uetool.EditAttrLayout$ShowMode.triggerActionUp(EditAttrLayout.java:195)
06-14 09:43:41.749 14803-14803/com.dstcar.client W/System.err:     at me.ele.uetool.EditAttrLayout.onTouchEvent(EditAttrLayout.java:65)
        at android.view.View.dispatchTouchEvent(View.java:11789)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
06-14 09:43:41.750 14803-14803/com.dstcar.client W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:451)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3389)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:413)
        at android.view.View.dispatchPointerEvent(View.java:12030)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4844)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4186)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4239)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4205)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4332)
06-14 09:43:41.751 14803-14803/com.dstcar.client W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4213)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4389)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4186)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4239)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4205)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4213)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4186)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6717)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6691)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6823)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
06-14 09:43:41.752 14803-14803/com.dstcar.client W/System.err:     at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6597)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "me.ele.uetool.fresco.UETFresco" on path: DexPathList[[zip file "/data/app/com.dstcar.client-LLzCx_HjySq2vN6MrXVVgQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.dstcar.client-LLzCx_HjySq2vN6MrXVVgQ==/lib/arm64, /system/lib64, /vendor/lib64]]
06-14 09:43:41.753 14803-14803/com.dstcar.client W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 51 more

**Comment by richardissuperman** [comment]
你是不是有用到fresco, 如果是的话，应该要加这个到gradle上 ```debugCompile 'me.ele:uetool-fresco:1.0.15'```

**Comment by JeasonWong** [comment]
Did you try to add `debugCompile 'me.ele:uetool-fresco:1.0.15'` ?
