### ISSUE TITLE
demo run appear  could not found view  please select view again

### ISSUE THREAD

**Issue by jianhui1012** [eleme/UETool#40]
#### Description

java.lang.NoSuchFieldException: mGlobal
08-29 14:46:37.265 10216-10216/me.ele.uetool.sample W/System.err:     at java.lang.Class.getDeclaredField(Class.java:631)
        at me.ele.uetool.CollectViewsLayout.onAttachedToWindow(CollectViewsLayout.java:87)
08-29 14:46:37.270 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.View.dispatchAttachedToWindow(View.java:12115)
08-29 14:46:37.275 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
08-29 14:46:37.280 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
08-29 14:46:37.285 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2716)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1352)
08-29 14:46:37.290 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1144)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4730)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
        at android.view.Choreographer.doCallbacks(Choreographer.java:555)
        at android.view.Choreographer.doFrame(Choreographer.java:525)
08-29 14:46:37.295 10216-10216/me.ele.uetool.sample W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4947)

#### Reproduce

型号：GT-N5100
Android版本：4.1.2
运行demo-> 点击捕捉控件 ->点击控件 -> 提示could not found view  please select view again和堆栈信息
执行此处
```  Field mGlobalField = Class.forName("android.view.WindowManagerImpl").getDeclaredField("mGlobal");```

#### Other Comment

[Add anything else here]

**Comment by Bondigeeek** [comment]
型号：三星N9009
系统：android4.3
出现相同问题
