### ISSUE TITLE
gradle version 3.3, compile error 

### ISSUE THREAD

**Issue by zhuruyi2013** [eleme/UETool#74]
#### Description
项目比较老， gradle是3.3， 引入依赖编译报错
[Tell us about the issue]
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDevDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --multi-dex --output E:\eoa-client\source\app\build\intermediates\transforms\dex\dev\debug\folders\1000\1f\main E:\eoa-client\source\app\build\intermediates\transforms\ajx\dev\debug\jars\1\10\39677893c1817aa2d28d88aae622830584547797.jar 
......
E:\eoa-client\source\app\build\intermediates\transforms\ajx\dev\debug\jars\1\10\8ebfff61b929dfce7d0d690c8c5767117b26f827.jar E:\eoa-client\source\app\build\intermediates\transforms\ajx\dev\debug\jars\1\10\219f4406fca35f758ba4fce2df5df08ec4fcd5a8.jar E:\eoa-client\source\app\build\intermediates\transforms\ajx\dev\debug\jars\1\4\61c9e3282442508bdbbb5f050f8005d312f19732.jar E:\eoa-client\source\app\build\intermediates\transforms\ajx\dev\debug\jars\1\4\50f5d7b15ade99752239035a8e4ad641e8032416.jar}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexOutOfProcess$1(DexByteCodeConverter.java:197)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Android\Android Studio\jre\bin\java.exe'' finished with non-zero exit value 2
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
	... 1 more

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by JeasonWong** [comment]
不太像是 uetool 引起的？有问题可以继续沟通哈
